### ISSUE TITLE
[Request] Options to only show hotbar counts if needed

### ISSUE THREAD

**Issue by supersaiyansubtlety** [BlazingTwist/ItemCounts#1]
It'd be useful to have some options to only show item counts on the hotbar if certain conditions where met.
`showOnHotbar` could be changed from a boolean to an enum of `NEVER`, `ALWAYS`, `WHEN_MORE_THAN_ONE`, or `WHEN_MORE_THAN_HOTBAR_STACK`. 

A new `showOnSelectedSlot` option would also be nice, taking the same enum as `showOnHotbar`. It would be like `showOnHotbar` except override `showOnHotbar`'s behavior for the currently selected hotbar slot.

**Comment by BlazingTwist** [comment]
I really don't like the way Autoconfig displays enums, which is why I stuck with booleans originally.
You're right though, enums would be much better suited for the kind of configuration I want to provide.

Unfortunately, I don't hate autoconfig enough to build my own system. (been there, done that, won't do it again... yet)
So here's a pre-release https://github.com/BlazingTwist/ItemCounts/releases/tag/1.0.1
Added the option to show durability while I was at it.

**Comment by supersaiyansubtlety** [comment]
Thanks, the pre-release looks great!

Not sure what you mean in your edit about `showOnSelectedSlot`. What I was envisioning for `showOnSelectedSlot` was just like `showOnHotBar`, why would it have different options?

**Comment by BlazingTwist** [comment]
With "the 3 existing options" I meant `showActiveItemCount`, `showOffhandItemCount`, `showOnHotbar`
I initially read the issue as "replace the boolean with an enum for `showOnHotbar` and `showActiveItemCount`",
but then noticed that `showOnSelectedSlot` would be a 4th option instead.

I'm assuming that `showOnSelectedSlot` should include the off-hand slot as well?

**Comment by supersaiyansubtlety** [comment]
You can't select the offhand slot so I wouldn't think so?

I've also noticed that there are two "Show durability for offhand tool" options in 1.0.1, is that intentional?

**Comment by BlazingTwist** [comment]
> I've also noticed that there are two "Show durability for offhand tool" options in 1.0.1, is that intentional?

Hmm, I'm not seeing that on my end.
There should be 5 options and a dropdown for each type.

**Comment by supersaiyansubtlety** [comment]
![offhand-durability-1](https://user-images.githubusercontent.com/618276/150845228-4e3b6bbe-c0ee-4311-ac9c-e3fc0f6c7133.png)
![offhand-durability-2](https://user-images.githubusercontent.com/618276/150845231-23d3b494-b708-45b9-af26-c03e78157413.png)

**Comment by supersaiyansubtlety** [comment]
Is it supposed to be "Show durability of hotbar tools"?

**Comment by BlazingTwist** [comment]
oh, lol. copy paste.

**Comment by BlazingTwist** [comment]
Alright, one effectively complete re-write later. The code got a bit nicer and everything should be supported now.
https://github.com/BlazingTwist/ItemCounts/releases/tag/1.0.2

**Comment by supersaiyansubtlety** [comment]
Nice!

The categories and toggles are definitely a nice touch.

**Comment by supersaiyansubtlety** [comment]
(guess this can be closed now)
