### ISSUE TITLE
Please fix it

### ISSUE THREAD

**Issue by QueenUlyana** [BlazingTwist/ItemCounts#11]
The way you made the number display in the hotbar is just awful. My inner perfectionist is terrified. Please do this that according to the standard, the numbers start "in the upper left corner" and then, when increased, they are added from the right side, BUT did not shift. It's so logical, but for some reason you didn't do it. Setting up in your mod is useless in this regard, from the word "absolutely".

![2023-06-01_21 21 18](https://github.com/BlazingTwist/ItemCounts/assets/83131824/e373b894-ee91-4087-b5a2-cc4d7f14a1af)

**Comment by QueenUlyana** [comment]
I repeat, the settings in your mod are useless.
![2023-06-01_21 30 45](https://github.com/BlazingTwist/ItemCounts/assets/83131824/adf9512e-101d-4318-b080-36c4f6303ed2)

**Comment by QueenUlyana** [comment]
@BlazingTwist  I would like it to be something like this.
![2023-06-01_21 32 46](https://github.com/BlazingTwist/ItemCounts/assets/83131824/c050aa74-abf4-4c43-bc71-2cd18df68e6a)

**Comment by BlazingTwist** [comment]
read the wiki, it's not that hard. https://github.com/BlazingTwist/ItemCounts/wiki/Configuring-an-Overlay

(if you wanted a nicer response, you should work on your ticketing.)

**Comment by QueenUlyana** [comment]
> read the wiki, it's not that hard. https://github.com/BlazingTwist/ItemCounts/wiki/Configuring-an-Overlay
> 
> (if you wanted a nicer response, you should work on your ticketing.)

I sincerely apologize to you. I'm an inattentive fool. There is one wish for the future update of your mod, the ability to change the color of the numbers.

**Comment by QueenUlyana** [comment]
> Alright, I'm assuming you figured out how the anchor works.
> 
> > change the color of the numbers
> 
> Sure, I can do that. One question though: what about items with durability? (Since these go from green to red text color) I can think of 3 ways to handle those:
> 
> 1. Add an option to toggle between durability-color and custom-color.
> 2. Add 3 configurable colors, for 'normal items', 'low durability' and 'high durability'
> 3. Apply some kind of blending between the custom color and the durability color (e.g. multiplying) - I think this option would just look bad in most cases.

To be honest, I do not know, since I do not use the "show durability" option. I have a mod "Simple Durability Tooltip" it shows me the durability on objects.

**Comment by BlazingTwist** [comment]
Added. Uploaded to curseforge for mc 1.18.0 - 1.19.4.
These files should become visible in a few hours or so.
