### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [BlazingTwist/ItemCounts#17]
versiyon; itemcounts-1.4.0+mc1.20.1
[crash-2023-07-23_03.16.42-client.txt](https://github.com/BlazingTwist/ItemCounts/files/12137438/crash-2023-07-23_03.16.42-client.txt)
[latest.log](https://github.com/BlazingTwist/ItemCounts/files/12137439/latest.log)
[rei.log](https://github.com/BlazingTwist/ItemCounts/files/12137440/rei.log)
[rei-issues.log](https://github.com/BlazingTwist/ItemCounts/files/12137441/rei-issues.log)

**Comment by BlazingTwist** [comment]
Thanks - gotta love mixins...
For now, all I can suggest is to use 1.3.0 instead [download](https://legacy.curseforge.com/minecraft/mc-mods/item-counts-fabric/files/4601200)

For some reason it works fine when started from the IDE (where it would be easy to debug), but does not work when started from the launcher (which is less easy to debug).

**Comment by BlazingTwist** [comment]
Okay, found the issue - it was silly.
Fixed mod for 1.20.1 will be available [here](https://legacy.curseforge.com/minecraft/mc-mods/item-counts-fabric/files/4660799)

**Comment by BlazingTwist** [comment]
Please elaborate, as it's working fine on my end.

**Comment by Rogenar** [comment]
ok problem solved. Since I had a crash caused by simple pipe and pipe plus mods, I removed these two mods and the game was fixed.
