### ISSUE TITLE
Can you update this mod to 1.20.2

### ISSUE THREAD

**Issue by lerokko** [BlazingTwist/ItemCounts#19]
Its is really friggin awesome.

**Comment by lerokko** [comment]
Edit: 1.20.3, 1.20.4, heck maybe even 1.21 when it comes out.

**Comment by BlazingTwist** [comment]
Oof. Been really busy lately.
Crazy that this Issue is a month old already. I'll try to make some time this week.

**Comment by BlazingTwist** [comment]
Welp, looks like the mod is still working without any changes. [curseforge download](https://www.curseforge.com/minecraft/mc-mods/item-counts-fabric/files/4660799)
Just make sure fabric-api and cloth-config are the correct version [(check the wiki)](https://github.com/BlazingTwist/ItemCounts/wiki/Tested-Versions)

What are you using to install mods that it didn't work?

**Comment by parcheesi15** [comment]
I'm having an issue with the off-hand aspect of ItemCounts. On version 1.20.4 I am able to have all of the features work with the main-hand and hotbar but when enabling the off-hand settings the item count is not showing up on the hotbar or next to the crosshair. Any ideas?

**Comment by BlazingTwist** [comment]
> I'm having an issue with the off-hand aspect of ItemCounts. On version 1.20.4 I am able to have all of the features work with the main-hand and hotbar but when enabling the off-hand settings the item count is not showing up on the hotbar or next to the crosshair. Any ideas?

I can think of a few possibilities for the overlay to not show even when enabled:
- `Show Item-Count` and `Show Item-Icon` are disabled.
- The configured offset is a large number (e.g. 1000 or -1000)
- The Scale-Factor is set to 0
- You configured a transparent text color (although I don't think that's possible)

Can you post a screenshot of your settings?
These default-settings seem to work for me.
![0cCUIm7tfu](https://github.com/BlazingTwist/ItemCounts/assets/39350649/eb7a6f0c-0251-45aa-9c64-57ae244f4f34)

**Comment by parcheesi15** [comment]
I was using all default settings other than the setting you have pictured above for "Configure overlay relative to crosshair for offhand item" which I had set to Yes. https://prnt.sc/SCP3fm5CldVa

Upon further investigation, I think it may be another mod that is not compatible for specifically just the off-hand feature. I am able to use all of the other features with my mods except off-hand. When I load a fabric client with just the ItemCounts mod, I am able to get the off-hand feature working properly. 

I will let you know if I figure out which mod it is fighting with. Thank you!

**Comment by BlazingTwist** [comment]
Alright, I'll close this issue now, since the original problem (a version for 1.20.2) seems to be solved.

If you do find which mod causes incompatibility, feel free to open a new issue, I'll have a look then.
