### ISSUE TITLE
Support for 1.20.6

### ISSUE THREAD

**Issue by EgorkaSanyok** [BlazingTwist/ItemCounts#20]
Hi there! Thank you for developing this great mod!
I would like to know if there are any plans of porting it to 1.20.6?

**Comment by BlazingTwist** [comment]
_I suppose it was time for a minecraft update to break my mods again._

NBT data on ItemStacks was changed (seems to work from my own testing)
Item/Text rendering was changed was well. (here I'm seeing an issue where text sometimes renders on top of other UI, which is annoying, but I don't know how to fix it, so _shrugs_ )

I'm putting this up as a pre-release - seems to work fine but do tell if it breaks with your configuration.
https://github.com/BlazingTwist/ItemCounts/releases/tag/1.4.1-mc1.20.5
https://github.com/BlazingTwist/ItemCounts/wiki/Tested-Versions

**Comment by EgorkaSanyok** [comment]
Thank you, I'll give it a shot!

**Comment by EgorkaSanyok** [comment]
The pre-release worked fine on 1.20.6! Would there be any plans for updating it to 1.21 as well?
