### ISSUE TITLE
Option to disable new "+" option

### ISSUE THREAD

**Issue by lerokko** [BlazingTwist/ItemCounts#24]
I really love the new + thing that excludes items currently in the hotbar.

However I also use this mod a lot to count items quickly for builds (and people "orderings" stuff from on on my server"). So this mod plus itemscroller made it very easy to just grab "518 red wool".

With the new change I would constantly have to add 64 in my head, so a config option to toggle it on or off would be greatly appreciated :D

**Comment by BlazingTwist** [comment]
> the new + thing that excludes items currently in the hotbar.

I'm not entirely sure what you mean by that.
Maybe `MORE_THAN_HOTBAR`? https://github.com/BlazingTwist/ItemCounts/wiki/Configuring-an-Overlay#show-item-count

In general, I'm pretty sure that if a count is shown, then it's always the total\* you have in your inventory.

###### \* the total according to your counting rules, that is https://github.com/BlazingTwist/ItemCounts/wiki/Counting-Rules

**Comment by lerokko** [comment]
Itemcounts used to show the inventory total in older versions. This was useful cause I could see ad a glance how many items are in my inventory. Now the sum excludes the times shown in the hotbar. If I want to know the total I have to add the counts in my hotbar in my head.

![image](https://github.com/user-attachments/assets/a14fd90a-95f9-4284-a07a-6482429779c6)
![image](https://github.com/user-attachments/assets/b5683739-aac8-428b-b28d-44f451ac3e02)

In older version the number displayed by item counts for golden carrots would be `89` (64+25=89) and not it is `+25`.
This is regardless of the option I select in `Show item-count`

(I am using version 1.4.1+mc1.21)

**Comment by lerokko** [comment]
Excuse my mistake. This was another mod. I did not find the config option that mentioned this feature but I now confirmed your mod works correctly.
