### ISSUE TITLE
feature request : hotkey to display item amount near crosshair

### ISSUE THREAD

**Issue by malovered** [BlazingTwist/ItemCounts#25]
i usually prefer to have total item amount displayed in the hotbar, but when i build it's more convenient to have it displayed near the crosshair
going to the mod options everytime is kind of tedeious so:
i'd like it if i could hit a hotkey and have item count show up near the crosshair, then hit it again and have it removed from there

**Comment by BlazingTwist** [comment]
Welp, this took all day... anyways it's up on curseforge. (version 1.5.0)
See also: [Wiki-Page: Configuring an Overlay - Hotkeys](https://github.com/BlazingTwist/ItemCounts/wiki/Configuring-an-Overlay#hotkeys)
