### ISSUE TITLE
[Request] Config toggle for ignoring metadata when calculating totals

### ISSUE THREAD

**Issue by roberestarkk** [BlazingTwist/ItemCounts#3]
G'Day!

It'd be nice if we could say "Don't include items in the total if they don't match on metadata/name/damage too", as I have plugins that use sticks and things for plugin-specific items. 
So I don't want to see a 6 'total' on a special item, when really I only have 1 of that special item, and 5 of the 'base' type.

Cheers :)

**Comment by BlazingTwist** [comment]
Hey there! Sorry for leaving this on read for so long, time sure flies.

Anyway, you'll now find a new tab 'Rules' in the settings, allowing you to count items separately if they have different [NBT tags, display name, remaining durability].
The curseforge release is currently under review.
