### ISSUE TITLE
[Request] Toggle to hide superfluous totals

### ISSUE THREAD

**Issue by roberestarkk** [BlazingTwist/ItemCounts#4]
G'Day!

It'd be neat if we could say "Don't show the 'total' total if all of the items are already on the hotbar/in this stack".
If I've just got the one sword, I don't need it to say '1' there. 
Similarly if I've just got the one stack of 32 porkchops, I don't need it to say 32 twice.

Cheers!

**Comment by BlazingTwist** [comment]
https://github.com/BlazingTwist/ItemCounts/releases/tag/1.0.2 does have "more_than_stack" and "more_than_one" rules.

I could add an additional "more_than_hotbar" rule

**Comment by roberestarkk** [comment]
Actually all of my use-cases are covered by more_than_stack. 
I don't actually mind seeing the grand total even if some other stacks are on the hotbar, as long as it's more than a stack it makes sense.
Thanks! :D
