### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sternschnaube** [BlazingTwist/ItemCounts#8]
Hello, thanks for this great mod 😊

To my suggestions:
Items with a counter of one, should not receive the item count number. It's really senseless.
On my example screenshot, the sword has this behaviour already - but other items (it should count for every item) should get that as well.
Second - items you have only in your hotbar (not exceeding her number within the inventory) should also not receiving the item count number. Rockets, flesh and signs are the example here.
Third - specific position for each number lenght (1,10,100,1000).
This way I could always setup the number in front top. Right now the number is with every lenght step a bit moving.

First and second is really important for me, and would turn the mod much greater as it is already - thanks.

![2023-01-16_03 09 04](https://user-images.githubusercontent.com/120551916/212583739-9baac928-cf4e-4b0b-9840-61412e0d668c.png)

**Comment by BlazingTwist** [comment]
1. The 'show item-count' option `MORE_THAN_ONE` covers this.
2. This is kind-of covered by `MORE_THAN_STACK`,
  but I could add an additional option for when you have two stacks of the same item in your hotbar.
3. I'll look into setting up an anchor system

**Comment by sternschnaube** [comment]
Thanks for the fast answer.
Looks much better now, great. 
Would be great if you could add that - from my second suggestion.
I'm looking forward to it 🥰

![image](https://user-images.githubusercontent.com/120551916/212592049-17f1b202-9b30-444a-89f9-923bda6330c9.png)

**Comment by BlazingTwist** [comment]
Alright, from version 1.2.0 onwards these changes are added:
2. 'show item-count' now has the option `MORE_THAN_HOTBAR`
3. you can now specify horizontal anchor positions under 'Configure offset'
Curseforge release will be updated soon-ish.

**Comment by sternschnaube** [comment]
Thank you so much 🥳
